# ===============================
# SERVER
# ===============================
server.port=8081

# ===============================
# SPRING APPLICATION
# ===============================
spring.application.name=renault-app

# ===============================
# DATABASE (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/renault_db
spring.datasource.username=postgres
spring.datasource.password=Postgres123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# MULTIPART (Upload fichiers)
# ===============================
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ===============================
# TESSERACT OCR (Binome - Mouna)
# ===============================
tesseract.datapath=C:\\Program Files\\Tesseract-OCR\\tessdata

# ===============================
# LOGGING
# ===============================
logging.level.com.renault.app=DEBUG
logging.level.org.springframework.web=INFO

# ===============================
# JWT - SECURITE (TOI)
# ===============================
jwt.secret=renault-secret-key-2024-ne-pas-partager-en-production-renault-app-jwt
jwt.expiration=86400000
jwt.refresh-expiration=604800000

# ===============================
# EMAIL - OTP (TOI)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nawresjamaoui44@gmail.com
spring.mail.password=NNzs6016++
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# OTP CONFIG (TOI)
# ===============================
otp.expiry-minutes=5
otp.max-attempts=3

# ===============================
# KEYCLOAK CONFIGURATION
# ===============================
keycloak.auth-server-url=http://localhost:8080
keycloak.realm=renault-realm
keycloak.resource=renault-app
keycloak.credentials.secret=FoU1knP7zmuL6ioZfkiScX7SCicZxQVg

# JWT Validation (Resource Server)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/renault-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/renault-realm/protocol/openid-connect/certs

# Keycloak Admin (pour creer users depuis le backend)
keycloak.admin.username=admin
keycloak.admin.password=admin123
keycloak.admin.client-id=admin-cli